/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NtButton: typeof import('@asteres/neatui-vue')['Button']
    NtInput: typeof import('@asteres/neatui-vue')['Input']
    NtTooltip: typeof import('@asteres/neatui-vue')['Tooltip']
  }
  export interface ComponentCustomProperties {
    vClickoutside: typeof import('@asteres/neatui-vue')['Clickoutside']
  }
}
